### ISSUE TITLE
FART is blowing up with the reobfShadowJar task

### ISSUE THREAD

**Issue by mysticdrew** [MinecraftForge/ForgeAutoRenamingTool#28]
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 38, end 37, length 37
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4601)
	at java.base/java.lang.String.substring(String.java:2704)
	at java.base/java.lang.String.substring(String.java:2677)
	at net.minecraftforge.fart.internal.EntryImpl$ClassEntry.<init>(EntryImpl.java:49)
	at net.minecraftforge.fart.api.Transformer$ClassEntry.create(Transformer.java:201)
	at net.minecraftforge.fart.internal.RenamerImpl.lambda$run$1(RenamerImpl.java:91)
	at net.minecraftforge.fart.internal.Util.forZip(Util.java:19)
	at net.minecraftforge.fart.internal.RenamerImpl.run(RenamerImpl.java:84)
	at net.minecraftforge.fart.Main.main(Main.java:159)
	
	FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':reobfShadowJar'.
> Process 'command 'C:\Program Files\Eclipse Adoptium\jdk-17.0.2.8-hotspot\bin\java.exe'' finished with non-zero exit value 1

```
I am not sure if this is an issue with FG6 or FART, I created this issue here because the exception is caused by FART. 

Using FG6, Gradle 8.1.1, Shadow 8.1.1
This is my shadowJar block

```
shadowJar {
    archiveFileName.set("${archiveBaseName.get()}-${archiveVersion.get()}-${project.loader_name}.${archiveExtension.get()}")
    configurations = [project.configurations.shade]
    archiveClassifier.set("shadow")
    dependencies {
        exclude("META-INF/maven/**")
        exclude("META-INF/services/**")
    }
    minimize {
        // API has utility classes that must be included
        exclude(dependency("info.journeymap:.*:.*"))
    }

    relocate "ar.com", "info.journeymap.shaded.ar.com"
    relocate "com.sparkjava", "info.journeymap.shaded.com.sparkjava"
    relocate "javax.servlet", "info.journeymap.shaded.org.javax.servlet"
    relocate "org.intellij", "info.journeymap.shaded.org.intellij"
    relocate "org.jetbrains", "info.journeymap.shaded.org.jetbrains"
    relocate "org.slf4j", "info.journeymap.shaded.org.slf4j"
    relocate "org.eclipse", "info.journeymap.shaded.org.eclipse"
    relocate "earcut4j", "info.journeymap.shaded.earcut4j"

    relocate "kotlin", "info.journeymap.shaded.kotlin.kotlin"
    relocate "spark", "info.journeymap.shaded.kotlin.spark"
    exclude 'LICENSE.txt'
}
```

**Comment by mysticdrew** [comment]
[journeymap-1.20-5.9.7-forge.zip](https://github.com/MinecraftForge/ForgeAutoRenamingTool/files/11691206/journeymap-1.20-5.9.7-forge.zip)
Github wont let me upload a jar. you will need to change the extension to jar.
